### ISSUE TITLE
Add Backlight switch for TS130F and ZM-L03E-Z

### ISSUE THREAD

**Issue by mrbluebrett** [Koenkk/zigbee-herdsman-converters#6370]
Hi, I have received a couple of 3 gang switches (1 for lights Zemismart ZM-L03E-Z - _TZ3000_lsunm46z), and one for curtain (Tuya TS130F - _TZ3000_8f8p9xbs).
Both paired well with Z2M and expose the functions. 
But I have found the backlights can be controlled changing the endpoint values. 
Both work with the same: 

- Endpoint: 1
- Cluster: OnOff
- Attribute: tuyaBacklightSwitch
- Value: 0 (off) / 1 (on)

This turns on and off completely the backlight (tested in dev console). Also note this is different from Backlight mode already present in TS130F. 
I think this can be changed in converters to expose this as a configuration switch, but I have 0 idea of how to do this.
Anyone can help me with this? I can test provided external converters...

**Comment by Koenkk** [comment]
> Also note this is different from Backlight mode already present in TS130F.

What's different?

**Comment by mrbluebrett** [comment]
Backlight modes are:
0 (low): blue when off, red when on
1 (medium): red when off, blue when on
2 (high): always blue

The backlight switch I’m talking about turns on/off the leds completely.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mrbluebrett** [comment]
I will test this Monday.
Thank you!

**Comment by mrbluebrett** [comment]
Hi, I tested today and I got an error:
![IMG_9414](https://github.com/Koenkk/zigbee-herdsman-converters/assets/77754688/79e0d0ae-b339-45b8-8f8d-d492fff6ac3f)
Also in the other light the control does not appear, and I realized now it reports as TS0003, not as ZM-L03E-Z. Not sure why it changed. But the thing is the backlight switch is not available there.

**Comment by mrbluebrett** [comment]
Can you re-open as this is not working as expected?

**Comment by Koenkk** [comment]
Pushed a fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mrbluebrett** [comment]
Yay! Now it works perfect!
Can we have the same for Tuya TS0003 (TZ3000_lsunm46z)?
Thank you very much!

**Comment by Koenkk** [comment]
Done!
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mrbluebrett** [comment]
I just updated the Edge version.
Still not present in Tuya TS0003 (TZ3000_lsunm46z)

**Comment by Koenkk** [comment]
What's the issue, does it now show up in the exposes tab?

**Comment by Koenkk** [comment]
Can you provide screenshots of:
- settings -> about tab
- device -> about tab
- device -> exposes tab

**Comment by mrbluebrett** [comment]
Here are the screenshots.

![IMG_9436](https://github.com/Koenkk/zigbee-herdsman-converters/assets/77754688/56d61cc0-9e0e-4e16-aeff-f92dd1b76578)
![IMG_9437](https://github.com/Koenkk/zigbee-herdsman-converters/assets/77754688/c234d0b8-b681-45a9-a99e-0c65e5e7c07a)
![IMG_9438](https://github.com/Koenkk/zigbee-herdsman-converters/assets/77754688/2fe45ec1-6e5f-4a42-8e43-1edeb0d948d3)


I hope that’s enough.

**Comment by Koenkk** [comment]
Found the issue, fixed it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mrbluebrett** [comment]
Yay! Now it works perfect on all!

**Comment by Trebor87** [comment]
Hello

I have several TS130F, even though the backlight is set to off, it's always on
Running HA supervisor 2024.04.0 and Sonoff dongle using Zigbee2MQTT Current version: 1.36.1-1

so any ideas how to swith the backlight off ?

thanks

![TS130F backlight](https://github.com/Koenkk/zigbee-herdsman-converters/assets/55857416/457610db-99e0-4f30-9769-87f2baebe3a5)

Zigbee Model  TS130F
Zigbee Manufacturer _TZ3000_ctbafvhm

**Comment by Trebor87** [comment]
hi

The backlights on my y curtain switches     TS130F Zigbee Manufacturer_TZ3000 are still always on, dimming or switches off does not work, whatever the settings chosen 
Running HA supervisor 2024.9.1 and Sonoff dongle using Zigbee2MQTT Current version: Firmware: 1.40.1

Any update on a  timeline when this can be dealt with ??

many thanks
