### ISSUE TITLE
'MAC transaction expired' (240) with Eurotronic Spirit SPZB0001 thermostat

### ISSUE THREAD

**Issue by vansoest** [Koenkk/zigbee-herdsman-converters#715]
Sporadic my Eurotronic Spirit SPZB0001 thermostat will not react on commands and throw an exception **'MAC transaction expired**' like:
`zigbee2mqtt:error 2019-10-25T10:07:50: Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
zigbee2mqtt:info  2019-10-25T10:07:50: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"thermostat/living_room"}}'
`

But If I change the temperature manually on the device itself, the transaction error will be fixed and reacting normal on set current_heating_setpoint:
`zigbee2mqtt:info  2019-10-25T10:19:56: MQTT publish: topic 'zigbee2mqtt/thermostat/living_room', payload '{"eurotronic_error_status":0,"current_heating_setpoint":19,"local_temperature":19.28,"occupied_heating_setpoint":20,"unoccupied_heating_setpoint":16,"eurotronic_system_mode":1,"pi_heating_demand":0,"battery":100,"linkquality":73,"system_mode":"heat"}'`

using hassio with zigbee2mqtt-edge docker image, but can not get the current git commit:
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/242
my latest version I assume is a few days old but already patched with the thermostat_system_mode feature! https://github.com/Koenkk/zigbee-herdsman-converters/pull/682
Coordinator: CC2531 zStack12 20190619

How to avoid this problem? The thermostat device is in the same room with the coordinator. The networkmap shows me a value from the coordinator to the device around 80-120.

**Comment by Koenkk** [comment]
This topic suggest to decrease the poll rate: https://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/158/t/674420?CC2531-How-to-wake-up-sleeping-MAC-layer- 

I've compiled a firmware with a polling rate of 200 ms (instead of 1000 ms), does it keep working now? Link to firmware: https://drive.google.com/open?id=1-M6Q7Nx3f5cMba91tqbf5Rmf7Qck_r_B

**Comment by vansoest** [comment]
Flashed and I got now  'No network route' (205)' for my thermostats. 
```zigbee2mqtt:error 2019-10-30T13:48:22: Publish 'set' 'system_mode' to 'thermostat/bathroom' failed: 'Error: Data request failed with error: 'No network route' (205)'
zigbee2mqtt:info  2019-10-30T13:48:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'system_mode' to 'thermostat/bathroom' failed: 'Error: Data request failed with error: 'No network route' (205)'","meta":{"friendly_name":"thermostat/bathroom"}}'

zigbee2mqtt:error 2019-10-30T13:53:48: Publish 'set' 'system_mode' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'No network route' (205)'
zigbee2mqtt:info  2019-10-30T13:53:48: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'system_mode' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'No network route' (205)'","meta":{"friendly_name":"thermostat/living_room"}}'
```

Ok I think the values are now corrupted. I reflashed now the version before: of the  Z-Stack_Home_1.2 CC2531_SOURCE_ROUTING_20190619 archive.

But now all seems broken. No device is communicating with the coordinator. Is there a way to fix it?

**Comment by vansoest** [comment]
all devices are now not working with the old and your firmware. I have also flashed another CC2531 now. It will also not work.

so you say I have to repair all 20 devices without a reason?

**Comment by vansoest** [comment]
I think the problem is solved I found no new errors inside the container log.

**Comment by sti0** [comment]
@Koenkk 
I've got the same issue from time to time. But I'm using a CC26X2R1 coordinator. Is it possible to decrease the poll rate for this coordinator, too?

**Comment by Koenkk** [comment]
@sti0 can you try replacing `/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js` with https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe . This should set the poll rate to 200.

**Comment by vansoest** [comment]
I got again the MAC transaction error but only for 1-2 thermostats. Other thermostats working well. But sometimes after a long time, it will break things. Rebooting the zigbee2mqtt service helped yesterday. Today the same error. Changing the temperature on the thermostat itself fixed the issue (again).

➜  ~ docker logs addon_7ad98f9c_zigbee2mqtt_edge | grep -i 'MAC transaction expired'
```
zigbee2mqtt:error 2019-12-29T12:21:23: Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
zigbee2mqtt:info  2019-12-29T12:21:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"thermostat/living_room"}}'
zigbee2mqtt:error 2019-12-29T12:22:01: Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
zigbee2mqtt:info  2019-12-29T12:22:01: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"thermostat/living_room"}}'
zigbee2mqtt:error 2019-12-29T12:23:47: Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
zigbee2mqtt:info  2019-12-29T12:23:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"thermostat/living_room"}}'
zigbee2mqtt:error 2019-12-29T12:25:04: Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
zigbee2mqtt:info  2019-12-29T12:25:04: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'thermostat/living_room' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"thermostat/living_room"}}'
```

Which kind of data do you need to find out what is the issue now?

**Comment by earion** [comment]
Same issue for me - I have 2 thermostats - one is working,  second is presenting Mac transaction expired

<pre>

gru 29 19:47:08 raspberrypi bash[6336]: zigbee2mqtt:debug 2019-12-29T18:47:08: Received MQTT message on 'zigbee2mqtt/termostat_gabinet/set' with data '{"current_heating_setpoint": 18.0}'
gru 29 19:47:08 raspberrypi bash[6336]: zigbee2mqtt:debug 2019-12-29T18:47:08: Publishing 'set' 'current_heating_setpoint' to 'termostat_gabinet'
</pre>
What boders me is that this device is still anouncing itself. Any idea?
Also what is strange for me that I don't have any readings about temperature from both devices


<pre>
gru 29 19:47:37 raspberrypi bash[6336]: zigbee2mqtt:debug 2019-12-29T18:47:37: Publishing 'set' 'current_heating_setpoint' to 'termostat_sypialnia'
gru 29 19:47:44 raspberrypi bash[6336]: zigbee2mqtt:error 2019-12-29T18:47:44: Publish 'set' 'current_heating_setpoint' to 'termostat_sypialnia' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
gru 29 19:47:44 raspberrypi bash[6336]: zigbee2mqtt:info  2019-12-29T18:47:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'termostat_sypialnia' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"termostat_sypialnia"}}'
gru 29 19:48:02 raspberrypi bash[6336]: zigbee2mqtt:debug 2019-12-29T18:48:02: Device 'termostat_sypialnia' announced itself
</pre>

My database.db here : https://pastebin.com/725ip5m5

**Comment by sti0** [comment]
> @sti0 can you try replacing `/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js` with https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe . This should set the poll rate to 200.

@Koenkk did this and there are no MAC-messages for a few days. Today I received one again. :-(

**Comment by sti0** [comment]
Today I've got another issue zigbee2mqtt responses with the MAC error. After pressing the hardware buttons the new temperature setpoint is delivered to zigbee2mqtt and visible in HA. But if I then try to set the temperature with zigbee2mqtt the MAC error responses again.

**Comment by earion** [comment]
For me fix with changing 

> > @sti0 can you try replacing `/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js` with https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe . This should set the poll rate to 200.
> 
> @Koenkk did this and there are no MAC-messages for a few days. Today I received one again. :-(

For mix this fix doesn't change anything. Is it possible that i have broken Spirit  device 
<pre>
sty 06 19:33:16 raspberrypi bash[6681]: zigbee2mqtt:debug 2020-01-06 19:33:16: Device 'termostat_sypialnia' announced itself
sty 06 19:33:23 raspberrypi bash[6681]: zigbee2mqtt:debug 2020-01-06 19:33:23: Received MQTT message on 'zigbee2mqtt/termostat_sypialnia/set' with data '{"current_heating_setpoint": 21.0}'
sty 06 19:33:23 raspberrypi bash[6681]: zigbee2mqtt:debug 2020-01-06 19:33:23: Publishing 'set' 'current_heating_setpoint' to 'termostat_sypialnia'
sty 06 19:33:29 raspberrypi bash[6681]: zigbee2mqtt:error 2020-01-06 19:33:29: Publish 'set' 'current_heating_setpoint' to 'termostat_sypialnia' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
sty 06 19:33:29 raspberrypi bash[6681]: zigbee2mqtt:debug 2020-01-06 19:33:29: Error: Data request failed with error: 'MAC transaction expired' (240)
sty 06 19:33:29 raspberrypi bash[6681]:     at ZStackAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:578:27)
sty 06 19:33:29 raspberrypi bash[6681]:     at Generator.next (<anonymous>)
sty 06 19:33:29 raspberrypi bash[6681]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:5:58)
sty 06 19:33:29 raspberrypi bash[6681]: zigbee2mqtt:info  2020-01-06 19:33:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'termostat_sypialnia' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"termostat_sypialnia"}}'
sty 06 19:33:35 raspberrypi bash[6681]: zigbee2mqtt:debug 2020-01-06 19:33:35: Saving state to file /opt/zigbee2mqtt/data/state.json
sty 06 19:33:48 raspberrypi bash[6681]: zigbee2mqtt:debug 2020-01-06 19:33:48: Device 'termostat_sypialnia' announced itself
</pre>

**Comment by PrivatHomeServer** [comment]
I'm looking for a solution too. We currently use three of these thermostats. We use a coordinator as CC3530 + router with external antenna. I'm not sure if I'm just getting it since the 1.8 update. But I installed two new devices yesterday. One is definitely not working...

> `zigbee2mqtt:info  2020-01-07 22:33:27: MQTT publish: topic 'zigbee2mqtt/Buero_HZ', payload '{"eurotronic_system_mode":1,"system_mode":"heat","linkquality":44,"local_temperature":20,"occupied_heating_setpoint":10,"unoccupied_heating_setpoint":16,"pi_heating_demand":0,"current_heating_setpoint":10,"eurotronic_error_status":0,"battery":100}'
zigbee2mqtt:error 2020-01-07 22:33:48: Publish 'set' 'current_heating_setpoint' to 'Buero_HZ' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
zigbee2mqtt:info  2020-01-07 22:33:48: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'Buero_HZ' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'","meta":{"friendly_name":"Buero_HZ"}}'`

**Comment by earion** [comment]
@PrivatHomeServer can You show log with debug on ?
Add in configuration
<pre>
advanced:
  log_level: debug
</pre>
I'm pretty sure that You will receive same issue as mine.

**Comment by Koenkk** [comment]
for cc2531 coordinator users: can you try with the firmware from https://github.com/Koenkk/zigbee-herdsman-converters/issues/715#issuecomment-547073703

**Comment by sti0** [comment]
@Koenkk I'm still using your suggested change (https://github.com/Koenkk/zigbee-herdsman-converters/issues/715#issuecomment-565814660) and it's not perfect but I noticed less MAC errors than without it. Would it be possible to set the poll rate by a parameter or would it be necessary to copy the changed startZnp.js file to my docker container after every restart?

**Comment by Koenkk** [comment]
@sti0 first i want to make sure this fixes the problem, can you change https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe#file-startznp-js-poll-rate-200-L214 `200` to `100` here and see if things improve?

**Comment by sti0** [comment]
> @sti0 first i want to make sure this fixes the problem, can you change https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe#file-startznp-js-poll-rate-200-L214 `200` to `100` here and see if things improve?

Changed it. Will come back to you in a few days.

**Comment by earion** [comment]
> @sti0 first i want to make sure this fixes the problem, can you change https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe#file-startznp-js-poll-rate-200-L214 `200` to `100` here and see if things improve?

For me that did't fix the issue

**Comment by sti0** [comment]
> @sti0 first i want to make sure this fixes the problem, can you change https://gist.github.com/Koenkk/ca4b55f33bb1727af6bda204b95feafe#file-startznp-js-poll-rate-200-L214 `200` to `100` here and see if things improve?

I had this running for over a week on the stable z2m 1.9 version and the errors appear only sometimes (around 20 errors / week). I set the local_temperature_calibration all day so this is quite a good result. 

I got the following errors:
> zigbee_publish_error: Publish 'set' 'local_temperature_calibration' to 'climate_schlafzimmer' failed: 'Error: Data request failed with error: 'MAC transaction expired' (240)'
> zigbee_publish_error: Publish 'set' 'local_temperature_calibration' to 'climate_schlafzimmer' failed: 'Error: Data request failed with error: 'MAC no ack' (233)'

THe errors appear on every of my three devices. Even there is an error, it "heals itself" and in the most cases not throw another error after.

This is not the perfect solution but way better than with a higher polling rate.

**Comment by Koenkk** [comment]
@sti0 you mean setting it twice right after each other fixes the issue?

**Comment by sjorge** [comment]
I'm nut running the modified pulling thing, but I have also noticed sometimes the TRV is slow to respond, poking it again immediately after the failure will work.

Maybe we give up to quickly? Or maybe it is in a deep sleep and needs a good kick or something.

**Comment by Koenkk** [comment]
@sjorge @sti0 if that indeed works, solving this command would be as easy as just adding `240` here https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L647

**Comment by sti0** [comment]
> @sti0 you mean setting it twice right after each other fixes the issue?

No, that's not the case. Sometimes if you set a value twice the error appears two times. But it's often the case that the second setting sets the value on the device (but the second setting could be a hour later). What I did ist to decrease the polling rate as you advised me (https://github.com/Koenkk/zigbee-herdsman-converters/issues/715#issuecomment-572426985). 

> @sjorge @sti0 if that indeed works, solving this issue would be as easy as just adding 240 here https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L647

If I understand the code, if we add `240`, the command is resend after a MAC error. This could possibly work. I will test this. But should I increase the polling rate back to standard? Could we log the success somehow?

As mentioned in my previous post (https://github.com/Koenkk/zigbee-herdsman-converters/issues/715#issuecomment-578602851) there is also a 233 error sometimes:

> zigbee_publish_error: Publish 'set' 'local_temperature_calibration' to 'climate_schlafzimmer' failed: 'Error: Data request failed with error: 'MAC no ack' (233)'

**Comment by Koenkk** [comment]
@sti0 

- yes change it back to the default
- if you don't see an error in the log it works
- also try adding `233` there (let's see if it improves)

**Comment by sti0** [comment]
@Koenkk ok, will do this at the weekend because I like to monitor the behavior.

**Comment by sti0** [comment]
@Koenkk I added 
`if ([225,233,240].includes(dataConfirm.payload.status) && attempt === 0) {`

at 
https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L647
and
https://github.com/Koenkk/zigbee-herdsman/blob/81ce0ec78c5203085257cdd02dddd360e4cce5a2/src/adapter/z-stack/adapter/zStackAdapter.ts#L698

but received to errors in the morning (both 240). The device responses successful some minutes later after I set the temperature calibration again.
Yesterday no errors appeared.

**Comment by Koenkk** [comment]
@sti0 maybe we should add a small delay before retrying, right before https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L653 and https://github.com/Koenkk/zigbee-herdsman/blob/81ce0ec78c5203085257cdd02dddd360e4cce5a2/src/adapter/z-stack/adapter/zStackAdapter.ts#L704 add: `await Wait(2000);` = 2 seconds.

**Comment by sti0** [comment]
@Koenkk added your suggestion and it seems to work fine but I received an 240 error last night (the 1st one since the wait adjustment). Do you have any other ideas?

**Comment by Koenkk** [comment]
I suggest to try up to 3 times (now 2), can you adapt the code (just duplicate the if statement for now).

**Comment by sti0** [comment]
Changed it into 
```
const dataConfirm = await response.promise;
if (dataConfirm.payload.status !== 0) {
    if ([225, 233, 240].includes(dataConfirm.payload.status) && attempt === 0) {
        /**
         * When many commands at once are executed we can end up in a MAC channel access failure
         * error (225). This is because there is too much traffic on the network.
         * Retry this command once after a cooling down period.
         */
        await Wait(2000);
        return this.dataRequest(
            destinationAddress, destinationEndpoint, sourceEndpoint, clusterID, radius, data, timeout, 1
        );
    } else {
        if ([225, 233, 240].includes(dataConfirm.payload.status) && attempt === 1) {
            /**
             * When many commands at once are executed we can end up in a MAC channel access failure
             * error (225). This is because there is too much traffic on the network.
             * Retry this command once after a cooling down period.
             */
            await Wait(2000);
            return this.dataRequest(
                destinationAddress, destinationEndpoint, sourceEndpoint, clusterID, radius, data, timeout, 2
            );
        } else {
            throw new DataConfirmError(dataConfirm.payload.status);
        }
    }
}
```

Is this what you meant?

**Comment by Koenkk** [comment]
I've made the changes in: https://gist.github.com/Koenkk/c4bdd09dec17f69e4702bff87b24399b

**Comment by sti0** [comment]
Thanks, I test it and will report.

**Comment by sti0** [comment]
@Koenkk another 240 error appeared with the changed version. I changed the wait time then to 2000ms but another error appeared.

**Comment by sjorge** [comment]
Just wondering, is the stick you are using one that support the updateRoute thing? If not, Maybe the old route doesn’t work at that point and until the trv sends and update no new route is established.

~ sjorge

**Comment by sti0** [comment]
I'm using a CC26X1 (https://www.zigbee2mqtt.io/information/supported_adapters.html#texas-instruments-cc26x2r1) with the 20191106 firmware.

**Comment by sjorge** [comment]
Nice, IIRC that does the new route discovery stuff... so I don’t think that could be an extra issue here, hmmmm

~ sjorge

**Comment by CodeFinder2** [comment]
I am having the same problem with only one of my devices (out of 5 total thermostats).

```text
zigbee2mqtt:error 2020-02-08 12:07:13: Publish 'set' 'current_heating_setpoint' to 'office/thermostat' failed: 'Error: Write 0x00158d0001ffc5c5/1 hvacThermostat({"16387":{"value":800,"type":41}}, {"timeout":10000,"defaultResponseTimeout":15000,"manufacturerCode":4151,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC transaction expired' (240))'
zigbee2mqtt:info  2020-02-08 12:07:13: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'current_heating_setpoint' to 'office/thermostat' failed: 'Error: Write 0x00158d0001ffc5c5/1 hvacThermostat({\"16387\":{\"value\":800,\"type\":41}}, {\"timeout\":10000,\"defaultResponseTimeout\":15000,\"manufacturerCode\":4151,\"disableDefaultResponse\":true}) failed (Error: Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"office/thermostat"}}'
```

Interestingly, the problematic device is very close (<1,5m clear line of sight) to my CC1352P-2 coordinator but I don't know if that really matters :thinking:

**Comment by sti0** [comment]
> Interestingly, the problematic device is very close (<1,5m clear line of sight) to my CC1352P-2 coordinator but I don't know if that really matters 

My most affected device is only ~0.5m away from the coordinator. Even clear sight.

**Comment by CodeFinder2** [comment]
Okay, the error already appeared again (less than 24h). I cannot control my thermostat through Z2M ... very annoying... :disappointed: 

Any ideas for a potential fix for this? Anything I can test?

**Comment by sti0** [comment]
> Okay, the error already appeared again (less than 24h). I cannot control my thermostat through Z2M ... very annoying... 
> 
> Any ideas for a potential fix for this? Anything I can test?

Could you please provide the firmware of the devices (https://github.com/Koenkk/zigbee2mqtt/issues/2500#issuecomment-583890805)

@Koenkk should we close the other issue (#2500) as it is duplicated?

**Comment by CodeFinder2** [comment]
@sti0 Sure, here they are:
```json
{"model":"SPZB0001","friendly_name":"office/thermostat","manufacturerID":4151,"manufacturerName":"Eurotronic","powerSource":"Battery","modelID":"SPZB0001","hardwareVersion":35,"softwareBuildID":"22190930","dateCode":"20191014","lastSeen":1581282174965}

{"model":"SPZB0001","friendly_name":"living_room/thermostat","manufacturerID":4151,"manufacturerName":"Eurotronic","powerSource":"Battery","modelID":"SPZB0001","hardwareVersion":35,"softwareBuildID":"22190930","dateCode":"20191014","lastSeen":1581282409805}
{"model":"SPZB0001","friendly_name":"bedroom/thermostat","manufacturerID":4151,"manufacturerName":"Eurotronic","powerSource":"Battery","modelID":"SPZB0001","hardwareVersion":35,"softwareBuildID":"22190930","dateCode":"20191014","lastSeen":1581268977482}
{"model":"SPZB0001","friendly_name":"kitchen/thermostat","manufacturerID":4151,"manufacturerName":"Eurotronic","powerSource":"Battery","modelID":"SPZB0001","hardwareVersion":35,"softwareBuildID":"22190930","dateCode":"20191014","lastSeen":1581268979268}
{"model":"SPZB0001","friendly_name":"bathroom/thermostat","manufacturerID":4151,"manufacturerName":"Eurotronic","powerSource":"Battery","modelID":"SPZB0001","hardwareVersion":35,"softwareBuildID":"22190930","dateCode":"20191014","lastSeen":1581282313434}
```

As you can see, all have the same hw/sw version :thinking: The first one is the one having this issue (hope the others won't be "infected" in the future :frowning: )

PS: I think closing the other issue is a good idea!

**Comment by sti0** [comment]
> I've made the changes in: https://gist.github.com/Koenkk/c4bdd09dec17f69e4702bff87b24399b

@Koenkk running this for a week now and I've got <10 MAC errors so I think this implementation is way better than the actual state. I publish local_temperature_calibration all day long and change the temperature several times a day. So I think that's a pretty good value (nothing is perfect ;-)).

I modified your gist and increased the attempts to 4 and wait time to 2000 sec. Maybe we could increase to 5 attempts and get rid of the other errors.
```
const dataConfirm = await response.promise;
        if (dataConfirm.payload.status !== 0) {
            if ([225, 233, 240].includes(dataConfirm.payload.status) && attempt <= 4) {
                /**
                 * When many commands at once are executed we can end up in a MAC channel access failure
                 * error (225). This is because there is too much traffic on the network.
                 * Retry this command once after a cooling down period.
                 */
                await Wait(2000);
                return this.dataRequest(
                    destinationAddress, destinationEndpoint, sourceEndpoint, clusterID, radius, data, timeout,
                    attempt + 1
                );
            } else {
                throw new DataConfirmError(dataConfirm.payload.status);
            }
        }
```

**Comment by CodeFinder2** [comment]
Surprisingly, mine started working again (no  such errors yet/anymore) for no obvious reason! (Note that previously I was not even able to change the temperature via HA regardless of how often I tried...very mysterious 😅

**Comment by Koenkk** [comment]
@sti0 can you try changing it to 5? How many request did you do in total now? (want to calculate what percentage failed)

**Comment by sti0** [comment]
@Koenkk I will change it to 5 and will record the number of changes. I calibrate the temperature if room or thermostat temperature changes. So this could be very often every day.

Let me run this till Sunday and I will post the results.

**Comment by sti0** [comment]
@Koenkk after running this setup (https://gist.github.com/sti0/a7a5ff9825ba4476a0ffced53d3400e1) for 89h I received 2x MAC 233 and 2x MAC 240 errors. I executed commands 1093 times for all three devices (364.3 calls/device, ~4 calls/hour).

**Comment by Koenkk** [comment]
@sti0 big thanks for this, added!

**Comment by Koenkk** [comment]
@sti0 I've changed the code a bit, could you check if this causes some regression on your side? (try with latest dev branch).

**Comment by sti0** [comment]
@Koenkk will test this at the weekend.

**Comment by sti0** [comment]
@Koenkk is this change already included in z2m 1.11.0 ?

**Comment by Koenkk** [comment]
@sti0 yes

**Comment by sti0** [comment]
@Koenkk OK, installed it today. I will report if there are any issues

**Comment by MrMennens** [comment]
I seem to have the same issue...
I'm running:
```
zigbee2mqtt:info  2020-03-27 10:23:11: Starting zigbee2mqtt version 1.7.1+dev (commit #ba18c5f773c160b54977908ed241cd40547a2fff)
zigbee2mqtt:info  2020-03-27 10:23:11: Starting zigbee-herdsman...
zigbee2mqtt:info  2020-03-27 10:23:12: zigbee-herdsman started
zigbee2mqtt:info  2020-03-27 10:23:12: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}}'
```
And this happens:
```
zigbee2mqtt:error 2020-03-27 10:23:20: Failed to configure '0x00158d0001cd2251', attempt 1 (Error: Data request failed with error: 'MAC transaction expired' (240)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:522:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:5:58))
```

after reading through the posts, i'm not sure where to edit what to get it working again..

Thanks in advance!

**Comment by Koenkk** [comment]
First make sure you are on the latest zigbee2mqtt

**Comment by MrMennens** [comment]
> First make sure you are on the latest zigbee2mqtt

I'm not able to update zigbee2mqtt (dev) to a version higher then my own version (1.7.1+dev)
and my coordinator version also seems up to date...

so not sure what to update to the latest? (should i use the none-dev version?)

**Comment by Koenkk** [comment]
1.7.1 is an old version, I would recommend to update to 1.12.0 or 1.12.0-dev.

**Comment by MrMennens** [comment]
> 1.7.1 is an old version, I would recommend to update to 1.12.0 or 1.12.0-dev.

Sadly the plugin doesn't update itself to the newest version..

https://github.com/danielwelch/hassio-zigbee2mqtt

I'll try and re-install them, see what happens..

**Comment by CodeFinder2** [comment]
By the way, my "'MAC transaction expired' (240))" errors seem to be gone, great!

**Comment by sti0** [comment]
> By the way, my "'MAC transaction expired' (240))" errors seem to be gone, great!

Yes, I didn't noticed these errors since a while. But I'm struggling with this one
`error 2020-03-28 05:10:50: Publish 'set' 'local_temperature_calibration' to 'climate_schlafzimmer' failed: 'Error: Write 0x00158d0001ffc423/1 hvacThermostat({"localTemperatureCalibration":25}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 5000ms)'`

Only this device responses with this kind of error. Both other ones didn't raised such an error. Don't know if the device has a bad connection. It's in the room next to the coordinator and there is one Hue bulb in this room. On the network map it is connected with the coordinator (CC26X2R1) instead the Hue bulb. Repairing and resetting doesn't seem to help.

**Comment by Koenkk** [comment]
@sti0 can you try with this firmware: 
[znp_CC26X2R1_LAUNCHXL_tirtos_ccs_20200328.hex.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4399544/znp_CC26X2R1_LAUNCHXL_tirtos_ccs_20200328.hex.zip)

**Comment by CodeFinder2** [comment]
@sti0 very interessting, now that you mention this: I was having this (or at least a similar) error for a few days too (but can't find it in my logs anymore :-/ ). However, it disappeared from one day to another for no reason. It was very annoying since it didn't allow me to control my device it, like in your case, only happend with 1 out of 5 devices...

**Comment by sti0** [comment]
> @sti0 can you try with this firmware:
> [znp_CC26X2R1_LAUNCHXL_tirtos_ccs_20200328.hex.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4399544/znp_CC26X2R1_LAUNCHXL_tirtos_ccs_20200328.hex.zip)

Thank you. This firmware works great. No error in the last 15h. The zigbee network seems to be more stable and it feels like motion sensors transmit signals faster. I will give you another feedback in the next few days.

**Comment by CodeFinder2** [comment]
Got this error again (z2m dev from yesterday, fw 20191106):
```
zigbee2mqtt:debug 2020-03-31 07:36:59: Publishing 'set' 'current_heating_setpoint' to 'office/thermostat'
zigbee2mqtt:error 2020-03-31 07:37:04: Publish 'set' 'current_heating_setpoint' to 'office/thermostat' failed: 'Error: Write 0x00158d0001ffc5c5/1 hvacThermostat({"16387":{"value":500,"type":41}}, {"timeout":6000,"manufacturerCode":4151,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 5000ms)'
zigbee2mqtt:debug 2020-03-31 07:37:04: Error: Write 0x00158d0001ffc5c5/1 hvacThermostat({"16387":{"value":500,"type":41}}, {"timeout":6000,"manufacturerCode":4151,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 5000ms)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:150:23)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
```

@Koenkk do you have a firmware for the CC1352-P to test as well? 
Reflashing a firmware in this device doesn't still require repairing (zigbee 3 stack), right? (It's not mentioned [here](https://www.zigbee2mqtt.io/information/FAQ.html#what-does-and-does-not-require-repairing-of-all-devices) explicitly.) Sorry to ask (again) but I am bit branded on this topic... 😅

**Comment by Koenkk** [comment]
@CodeFinder2 as you long there is a `coordinator_backup.json` in your data directory repairing isn't necessary.

Firmware:
[znp_CC1352P_2_LAUNCHXL_tirtos_ccs_20200328.hex.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4410287/znp_CC1352P_2_LAUNCHXL_tirtos_ccs_20200328.hex.zip)

**Comment by CodeFinder2** [comment]
Honestly, this made me swet. :-D First of flashing worked and the backup was restored, so no repairing necessary, puh!

What's really interessing is that my device had the [above error](https://github.com/Koenkk/zigbee-herdsman-converters/issues/715#issuecomment-606426344) right before the firmware update. And before I updated, I restarted Z2M (just to try) which didn't fix the error. I then upgraded with your [given firmware](https://github.com/Koenkk/zigbee-herdsman-converters/files/4410287/znp_CC1352P_2_LAUNCHXL_tirtos_ccs_20200328.hex.zip) and the error was immediately gone: I was able to set a new temperature which wasn't possible with the old FW a few minutes ago, great! That thing seems to do the trick, thanks to @Koenkk ! Can you explain what you have changed in that new FW (basically)? Is this or will this become a "regular FW"? Asking because it's not listed [here](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) yet.

Side note: When you get the following error while flashing a firmware ([step 7](https://www.zigbee2mqtt.io/information/flashing_via_uniflash.html)):
```
Error! 
Unable to open file: C:/Users/a space in your path is bad/Downloads/znp_CC1352P_2_LAUNCHXL_tirtos_ccs_20200328/znp_CC1352P_2_LAUNCHXL_tirtos_ccs_20200328.hex
```
...make sure that there are no spaces in the path / file name (and maybe not too long) ... wtf, come on, its 2020?! 😆

**Comment by Koenkk** [comment]
Good to hear, when this fw is well tested it will indeed become the regular. Will update changelog later.

**Comment by Boldie** [comment]
I had some serious problems with the current firmware with paring Ikea tradfri devices, especially a bulp has never been paired. Good news: I used the firmware from above and now it works much better.

**Comment by CodeFinder2** [comment]
@Koenkk unfortunately, this is new (since I flashed [the new FW](https://github.com/Koenkk/zigbee-herdsman-converters/files/4410287/znp_CC1352P_2_LAUNCHXL_tirtos_ccs_20200328.hex.zip)):
```
zigbee2mqtt:debug 2020-04-03 22:42:44: Received MQTT message on 'zigbee2mqtt/living_room/couch_bulb/set' with data '{"state": "OFF"}'
zigbee2mqtt:debug 2020-04-03 22:42:44: Publishing 'set' 'state' to 'living_room/couch_bulb'
[...]
(node:715) UnhandledPromiseRejectionWarning: Error: Timeout - 62428 - 1 - 147 - 6 - 11 after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
zigbee2mqtt:error 2020-04-03 22:42:54: Publish 'set' 'state' to 'living_room/couch_bulb' failed: 'Error: Command 0xf0d1b8000010421c/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'MAC channel access failure' (225))'
zigbee2mqtt:debug 2020-04-03 22:42:54: Error: Command 0xf0d1b8000010421c/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'MAC channel access failure' (225))
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:339:23)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
zigbee2mqtt:info  2020-04-03 22:42:54: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'living_room/couch_bulb' failed: 'Error: Command 0xf0d1b8000010421c/1 genOnOff.off({}, {\"timeout\":6000,\"manufacturerCode\":null,\"disableDefaultResponse\":false}) failed (Error: Data request failed with error: 'MAC channel access failure' (225))'","meta":{"friendly_name":"living_room/couch_bulb"}}'
```

Getting a lot of these errors (for different devices: bulbs, thermostats, and smart plugs) and my network is kinda laggy now. It went really well for a day or two ... :thinking: 

- Restarting Z2M didn't help
- Reconnecting my CC1352P-2 **solved it (for now?)**

Once like always, please let me know if there's more I can test or if you need more information! ;-)

**Comment by sti0** [comment]
Can't confirm this for CC26X2R1 firmware. No errors since 5 days.

**Comment by Koenkk** [comment]
@codefinder2 could you provide a sniff when these errors happen?

**Comment by CodeFinder2** [comment]
Sure, will do and report here once the error occurs again!

**Comment by sti0** [comment]
Today I got this Promise Error, too. The whole network didn't response. Restarting zigbee2mqtt didn't solve the problem. Reconnecting the adapter while z2m is running didn't solve this. I stopped z2m, reconnected the adapter and started z2m back up. 

Somehow all logs before the first restart are deleted. Therefore I could not provide further information. (Did the rescue action with my smartphone...no lights in the whole house in the early morning 😨 )

**Comment by Boldie** [comment]
Now the same thing happened to me.

**Comment by CodeFinder2** [comment]
As Koenkk said, please provide a sniff log if possible...

**Comment by Boldie** [comment]
Which snifflog (Air, Serial, USB?) do you need and how to obtain it?

**Comment by CodeFinder2** [comment]
@Boldie https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by Boldie** [comment]
> @Boldie https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

Ok, zigbee traffic is of interest. Started my sniffer and now lets wait ... hopefully it does not quit sniffing in between like many times before. Used it without wireshark and just with output to file now on my server.

**Comment by Boldie** [comment]
No crash so far :/

**Comment by CodeFinder2** [comment]
Dito, really strange ...

**Comment by wassfila** [comment]
Hi,
I have the same issue since a long time. Today I discovered this discussion, while I was investigating it again.
Luckily, I could even reproduce it with wireshark trace if this can help anyone.

The wireshark and z2m logs are here :
[zigbee_eurotronic_issue.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4842335/zigbee_eurotronic_issue.zip)

I made the wireshark capture with an nRF52840 usb dongle which is cheap, available and can be directly flashed with boot on usb.

About sniffing in general, I could even document the sniffing [here](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html) if I can edit that, or someone could add it.

Now back to the issue, I could only note that the failing device is talking to the router not to the main coordinator directly, but could not really interpret all the communication.

**error 2020-06-28 14:50:01: Publish 'set' 'current_heating_setpoint' to 'living heat' failed: 'Error: Write 0x00158d000192dd3e/1 hvacThermostat({"16387":{"value":1100,"type":41}}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Error: Data request failed with error: 'MAC transaction expired' (240))'**


<img width="775" alt="Network" src="https://user-images.githubusercontent.com/1510763/85949111-23129300-b955-11ea-9e9e-a7e9480c8331.png">


## addresses helper
* 'living heat' (Eurotronic) failing device
  * 0x00158d000192dd3e / 00:15:8d:00:01:92:dd:3e
  * 0x21f3 = 8691

* coordinator : 'power lifo'
  * 0x00124b001d4a014b / 00:12:4b:00:1d:4a:01:4b
  * 0x0000
* router      : 'power router'
  * 0x00124b001c2f1279 / 00:12:4b:00:1c:2f:12:79
  * 0xd5b1 = 54705

* bathroom heat (Eurotronic) properly running device
  * 0x82f2= 33522

error time :
2020-06-28 14:50:01

**Comment by wassfila** [comment]
additional info, I can nevertheless update the heat in the eurotronic device but z2m does not publish any feedback from the device
```
* 2567	16:21:13.398690	0.008497	ZCL: Write Attributes, Seq: 33	00:12:4b:00:1d:4a:01:4b	0x0000	0x21f3	-64dBm	116	ZigBee HA	65	0xb0f4				81	✓	
* 2569	16:21:13.404913	0.005676	ZCL: Write Attributes Response, Seq: 33	00:15:8d:00:01:92:dd:3e	0x21f3	0x0000	-83dBm	44	ZigBee HA	71	0xb0f4				77	✓	
```
I have the full trace for this as well if needed, but the "'MAC transaction expired' (240)" error does not happen at the same time when updating the temperature on the device.

**Comment by allofmex** [comment]
Sadly I can't read your pcapng file in Wireshark.. Encapsulation type: Unknown (0)

> I could only note that the failing device is talking to the router not to the main coordinator directly, but could not really interpret all the communication.

Just a hint for interpreting the communication:
You may also add column `wpan.src16` and `wpan.dst16` to your Wireshark view (right click table head -> Column Preferences -> Appearance -> Columns -> + -> Field=wpan.dst16), example [here](https://github.com/Koenkk/zigbee2mqtt/issues/1408)

This may help to follow through the routing:
You may see multiple lines with same Source/Destination/Info but different wpan adresses. These are the single routing-"hops". Source/Destination address is let's say the full-way start/target address

For example: lets say device 0xaaaa sends to coordinator 0x0000 (source/destination), in wpan you will see that it in reality sent data first from 0xaaaa to its parent 0x0001, 0x0001 forwarded it to 0x0005, (...) 0x0005 to coordinator 0x0000.

I guess that the request (or its response) gets lost (or wrong routed)

**Comment by wassfila** [comment]
@allofmex , thanks for the hints on viewing the traces. I did even put some colored filters for tx rx on short address 16 and long 64.
I also put all logs z2m and wireshark traces on a github repo special for the issue analysis, hope you can get the pcap files, I redoanloded it from github and could still view it (of course either clone or download raw).
I'll keep observing wireshark to better understand the behavior and I'm reading z2m code on the other hand.

**Comment by allofmex** [comment]
> hope you can get the pcap files

Sorry, still can't read packets. Maybe custom encryption keys?

**Comment by wassfila** [comment]
So you mean you could open the capture file in wireshark but only could not see the zigbee payload which is encrypted ?
I thought about the encryption key, then did not mention it as I'm using indeed the default security kee for demo and sharing purpose.
![image](https://user-images.githubusercontent.com/1510763/86381001-152e7c00-bc8d-11ea-8b1a-8d624e85d142.png)

Now it could be that the wireshark dissector I'm using would have coded the data differently than your wireshark have opened them. I actually did not thought about that and expected the pcap file to be wireshark standard and not dissector specific.

For info I'm using [this Sniffer](https://cdn-learn.adafruit.com/assets/assets/000/059/041/original/nRF_Sniffer_User_Guide_v2.1.pdf?1533935335). [Github repo](https://github.com/NordicSemiconductor/nRF-Sniffer-for-802.15.4) from Nordic. If that is the issue then it would make sense that I stick to the commonly used wireshark capture for sharing traces.

**Comment by vansoest** [comment]
So I updated last week to the latest master and repaired the most of my devices. but the update had not solved the `MAC transaction expired` problem with my living room thermostat  — all others are working well.

The living room and bathroom thermostats are still connected directly to my coordinator. This is strange I have a lot of Tradfri Ikea routers (signalverstärker) normally they should connect automatically to the router(s)?
![Screenshot_2020-10-01-53_753x633](https://user-images.githubusercontent.com/574578/94797152-049eb680-03e0-11eb-9c5e-b7097bb18403.png)

**Comment by Koenkk** [comment]
@vansoest would you be able to sniff the traffic of both the working and non-working situation? This should give us more insight what the root cause of this problem is. (https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by xMariusz** [comment]
Any solition? I have the same problem:

`Zigbee2MQTT:error 2020-11-06 18:30:33: Publish 'set' 'system_mode' to '0x00158d00032f7f65' failed: 'Error: Write 0x00158d00032f7f65/1 hvacThermostat({"16392":{"value":33,"type":34}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null}) failed (Status 'INVALID_VALUE')'

Zigbee2MQTT:info  2020-11-06 18:30:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'system_mode' to '0x00158d00032f7f65' failed: 'Error: Write 0x00158d00032f7f65/1 hvacThermostat({\"16392\":{\"value\":33,\"type\":34}}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4151,\"transactionSequenceNumber\":null}) failed (Status 'INVALID_VALUE')'","meta":{"friendly_name":"0x00158d00032f7f65"},"type":"zigbee_publish_error"}'`

**Comment by idofr** [comment]
I fear I'm also experiencing the same issue.
Re-paring works for a bit and then stops.
How do I change the polling rate through HassOS?

**Comment by PrivatHomeServer** [comment]
I cannot control two of three thermostats for a while now. I changed my Zigbee Coordinator for better performance to an "cc2652rb". So everything looks good (linkquality). I also added the value "debounce: 0.5". It looks like the effect to get every 10 sec the json information from each thermostat. But in the end i have now the problem to control the therostats. In the log file seem everything okey. Do you have an idea?

**Comment by M-Tier** [comment]
For me using "occupied_heating_setpoint" works fine, while "current_heating_setpoint" also gives me "MAC transaction expired" OR "invalid_value" errors. 
I do not know what the difference between "occupied" and "current" exactly is, but using "occupied" fixed it for me.
Maybe this helps someone...

**Comment by wassfila** [comment]
@M-Tier I think I have workarounds this.
First answering your question about current vs occupied. Only the current is effective for the temp regulation, the occupied and unoccupied are simply user configuration with the convenience of being able to be stored on the device, so that different automation software could pick it from there consistently. e.g. you have one tool to configure occupied/unoccupied and another tool for presence detection or schedule and swaps the current according to the value configured in occupied/unoccupied.
My impression is without an external tool using them, I did not notice any effect on the device itself in case you only care about the current.

Now back to the issue of this topic, how do I fix it every time, 

- repair the device. Not fun, but you ought to be ready to repair every month or so, on the lucky case some devices run for more than a year, some others get lost after a week.
- repair is not easy, due to some mysterious bug I could never properly report (too complex), my z2m does not allow pairing devices neither old nor new ones, I even analyzed the wireshark traces and found an absurdity from z2m requesting the device to leave as soon as it gets first request, in order to workaround that, see next points :
- stop z2m, remove the zigbee adapter, wait 10 sec, re plug it, restart. This is even explained in z2m user guide, which to me shows the unexplained limitation, it is a firmware bug to me that might be hard to fix.
- remove the device before pairing it again
- keep the adapter as close as possible to allow proper attributes discovery

and now, if you want to have a happy long time using it without needing to repair again, most important is :
- keep your zigbee network clean
- make sure all your wifi routers are on a fixed freq far from the z2m zigbee freq
- keep checking signal quality (e.g. grafana below)
- ask your neighbors to stop using wifi

of course not all are possible so you might have to re-pair again when that error appear. Now of course as a product, it's insane that a user has to live with such a pain, well don't forget that the devices are not within their intended used scope so you have no official support here, we're on our own. Standards are not enough to guarantee interoperability, reporting this bug to the device manufacturer might not interest them, and no one has the capability to debug the z2m firmware interoperability with each device.

long story short, hope the workaround I suggested help, for the time being I decided that living with the workaround will take me much less time than trying to fix them, here's my projects github if you'd like to have more info about how I set up my heating system https://github.com/HomeSmartMesh/raspi

fileds|  
-- | --
current_heating_setpoint |  
occupied_heating_setpoint |  
unoccupied_heating_setpoint |  
eurotronic_system_mode |  
pi_heating_demand |  
eurotronic_error_status |  
battery |  
linkquality |  
local_temperature |  


![image](https://user-images.githubusercontent.com/1510763/100538082-d269d380-322d-11eb-93bb-b190e16a2c4d.png)

**Comment by wassfila** [comment]
This is probably offtopic but now that I started exposing usage examples for the Eurotronics, I post this here two, maybe people googling about it would find it, I forgot to mention that monitoring the "pi_heating_demand" is probably the most important parameter because that's where the money goes to, how much hot water flows in. In multiple cases, there is a flow passing although the temperature conditions do not require it, so that low maintenance could be cut. Also what we can see from the graphs below is that it might be a good idea to set the target temperature low even after the windows are closed in order to take advantage of heating up the air with the walls radiation, in other words, after closing the windows the temperature raises by itself to certain level even without heating, the pi heating demand taken at that time is kind of not needed / wasted, in this case not that high so does not matter much.
![image](https://user-images.githubusercontent.com/1510763/100538901-e2d07d00-3232-11eb-80c7-52c173b09359.png)

**Comment by M-Tier** [comment]
@wassfila 
Thank you for the very detailed description of your workaround. 
I will give that a try and keep you informed here, if I got any information on how to get it more stable.

**Comment by idofr** [comment]
I think I'm overseeing something, but the problem was somehow solved about 3 days ago, probably after an auto-update.
I've just spent some time going through the changelogs of
https://github.com/danielwelch/hassio-zigbee2mqtt
as well as the most recent ones of this repo and I couldn't find any reason for the issue to go away. I'm just really happy it finally did.

I hope someone reads this at some points and can maybe enlighten me with the relevant change.
But even if not, my general thanks for everyone who works hard on this repo :)
I'll make sure to update this message if the issue comes back at some point, but it has been around 3 days now and it seems solid.

**Comment by wassfila** [comment]
@idofr thanks for the info, hope it's fixed for you once and for all. I would not be that in a hurry to declare victory, because this issue has two folds, hidden mode, it can work fine for Months, then active mode where the issue can become noticeable, some times immediately after pairing some time after a long time.

**Comment by idofr** [comment]
Yes, I know, that's also the reason I've waited a few days before posting an update here.
It seems though I was too quick to react. That HomeAssistantOS update to 5.8 has broken everything. I have 3 different plugins including zigbee2mqtt completely unusable at the moment

**Comment by wassfila** [comment]
actually my main problem related to this issue was that I could not any any feedback from the devices and they stop reporting their attributes, this is now getting solved with  a reconfigure, which does not require repairing.

**Comment by M-Tier** [comment]
Update from my side (and happy new year by the way! 😄):
After updating zigbee2mqtt to the latest version last week the problem did NOT occur again so far. 
I did some penetration testing by doing actions, which definitely would have broken the functionality in the past (restarting the hosting Raspberry Pi, Re-Plugging the Zigbee Device etc.), which passed without any problems.

Of course this is just a small success and there is no guarantee, that it will still work next week, but I wanted to share the news with you.

Maybe someone, who also had this issue before (@wassfila @idofr ) can update and check, if it helps.

Otherwise I'm afraid I have to switch to another thermostat.

**Comment by idofr** [comment]
I fear i can't confirm. The latest update did come with a positive change and the thermostat ist now 1-2 times a day accessible. But most of the time I still can't reach it.
Thanks for the update though

**Comment by wassfila** [comment]
@M-Tier thanks for the info. Wish you the same a happy new year :)
I also have an update from my side, I realized I was pushing the coordinators to their limit, where it's unclear to me if what matters is the number of devices or rather the number of attributes bindings with all sensors to get their values. Long story short, I moved to a new coordinator (a CC2652 based) which can handle up to a 100 devices, I assisted him with two long range routers (GB2530) and I did not have any issues since
I described all coordinators I used here :
https://homesmartmesh.github.io/docs/networks/zigbee/#ti-based-dongles

The target of a good working setup is the coordinator not to loose any cluster attribute binding, and I felt that 1) if the pairing fail, the interview might miss some attributes which become unusable from the zigbee device. Also, it happened often that an attribute got lost, not sure if that was after a long bad connection or maybe the coordinator just failing with too many attributes bindings for its memory. And even then, I managed once to call a reconfiguration which brought some attributes back.

So if you could tryout another Thermostat, please do so, as the comparison might be interesting. But if you intend to use the thermostats reliably, it does not feel to me that Zigbee is the right protocol for you. A protocol based on discovery which relies on the network quality does not look to me as efficient as a TCP connection with hard-coded capabilities.

And by the way, as a fun fact, I developed an esp32 remote control for those thermostats
for those interested, details of the Platformio app here
https://homesmartmesh.github.io/docs/microcontrollers/esp32/ttgo-t-display/#thermostat-control
![image](https://user-images.githubusercontent.com/1510763/105208533-151e9c80-5b49-11eb-9949-5e7f353aedf9.png)

**Comment by DavidHamburg** [comment]
I can also confirm the error happens regulary with the latest dev branch of koenkk/zigbee2mqtt.

**Comment by lcuwx2016** [comment]
I have the same problem.
What is ‘MAC transaction expired’？

**Comment by popsodav** [comment]
Experiencing the same issue with two lumi.curtain.agl001 curtain drivers on CC2531 usb stick.
After re-pairing devices they work for 3-4 weeks, and issue happens once again.

**Comment by daniel-wojcik** [comment]
Unfortunatelly I have the same issue. I'm using CC2651R1 stick with latest firmware and latest Z2M. Aquara temp sensor works pretty well, but I extended my setup by 2 pieces of Tesla TV100 thermostatic valve. And after 2 weeks from pairing both started to show 'MAC transaction expired' errors. I re-paired them (it helped) and after 1 week I noticed that 1 of them started to show the same errors. Restart of Z2M fixed it.

**Comment by Sakriel** [comment]
+1 same problem here. Is there any fix for that?
