### ISSUE TITLE
[Wrong device]: LoraTap SC500ZB (pink version) detected as Tuya TS130F

### ISSUE THREAD

**Issue by Me-Hao** [Koenkk/zigbee-herdsman-converters#9640]
Link

https://www.zigbee2mqtt.io/devices/SC500ZB.html

Model
SC500ZB (pink version from Amazon germany)
https://www.amazon.de/dp/B0CZTW3JZ9

Description
Roller Shutter Blind Module

Vendor
LoraTap

Picture (link)
https://m.media-amazon.com/images/I/61mGeyaFeEL._SL1500_.jpg

Picture of manual (link)
https://ibb.co/4Z0T77XL

Database entry

{"id":17,"type":"Router","ieeeAddr":"0xa4c138eed9925b74","nwkAddr":10719,"manufId":4417,"manufName":"_TZ3000_femsaaua","powerSource":"Mains (single phase)","modelId":"TS130F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[4,5,6,258,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS130F","manufacturerName":"_TZ3000_femsaaua","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"tuyaBacklightSwitch":0,"tuyaBacklightMode":0}},"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":100,"tuyaMovingState":1,"tuyaCalibration":1,"tuyaMotorReversal":1,"moesCalibrationTime":274}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"interviewState":"SUCCESSFUL","meta":{},"lastSeen":1752815261341}

Notes
Like this one already solved.
https://github.com/Koenkk/zigbee2mqtt/issues/25996

Manual shows [SC500ZB-V3]([url](url))

Working almost well, but not recognized as expected.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by Me-Hao** [comment]
Hi,
this device is now shown as
Zigbee Model - TS130F
Zigbee Manufacturer - _TZ3000_femsaaua

The positioning is still not working correctly in ZigbeeToMQTT.
In manual mode, the position is shown correctly, but if I send this to a specific position. The shutter will complete close or open.

The second calibration time, like in V4, is still missing.
([https://www.zigbee2mqtt.io/devices/SC500ZB-v4.html](https://www.zigbee2mqtt.io/devices/SC500ZB-v4.html))

There is no OTA function available.

Is there something missing?

Thank you very much for your work!!
